description: "testx"
prompts:
  - file://prompt.json
providers:
  - "openai:gpt-4o"
tests:
  - vars:
      topic: avocado toast
    assert:
      - type: icontains
        value: avocado
  - vars:
      topic: new york city
    assert:
      - type: llm-rubric
        value: ensure that the output is funny
