prompts:
  - What is the capital of the {{country}}?

providers:
  - id: siliconflow:deepseek-ai/DeepSeek-R1-Distill-Llama-8B
    config:
      max_tokens: 128
      temperature: 0
  - id: siliconflow:deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
    config:
      max_tokens: 128
      temperature: 0

tests:
  - vars:
      country: United States
    assert:
      - type: icontains
        value: Washington, D.C.
  - vars:
      country: England
    assert:
      - type: icontains
        value: London
