name: release

on:
  release:
    types:
    - created

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup docker
        uses: docker/setup-buildx-action@v3
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          file: Dockerfile
          push: true
          tags: craftslab/testx:latest
