name: release

on:
  release:
    types:
    - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'source/.nvmrc'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          pushd source || exit 0
          npm publish
          popd || exit 0
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TESTX_NPM_TOKEN }}
  docker:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup docker
        uses: docker/setup-buildx-action@v3
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          file: Dockerfile
          push: true
          tags: craftslab/testx:latest
